# Generated by Django 4.1.7 on 2023-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_airports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airports',
            name='airportId',
        ),
        migrations.AddField(
            model_name='airports',
            name='code',
            field=models.CharField(default=1234, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='createdBy',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
