# Generated by Django 4.1.7 on 2023-03-06 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_airports_airportid_airports_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
